export const PROFILE_COPY = {
  en: {
    title: 'Profile Completion',
    lockedTitle: 'Profile Verification',
    subtitle: 'Complete all three steps to finalize your applicant profile.',
    lockedSubtitle:
      'Review your details and keep your contact preferences up to date.',
    lockedBanner:
      'Verification is in progress. Eligibility and academic fields are locked after application submission.',
    lockedHint: 'Locked after application submission',
    loadErrorTitle: 'We could not load your profile',
    retry: 'Try again',
    loading: 'Loading your profile…',
    complete: 'Profile complete',
    saved: 'Your profile has been saved.',
    saveErrorTitle: 'Your changes could not be saved',
    validationSummary: 'Check the highlighted fields and try again.',
    stepsAriaLabel: 'Profile completion steps',
    personalStep: 'Personal info',
    contactStep: 'Contact info',
    academicStep: 'Academic info',
    personalTitle: 'Personal information',
    contactTitle: 'Contact and preferences',
    academicTitle: 'Academic information',
    fullNameEn: 'Full name in English',
    fullNameAr: 'Full name in Arabic',
    nationalId: '14-digit National ID',
    nationality: 'Nationality',
    egyptian: 'Egyptian',
    dateOfBirth: 'Date of birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    militaryStatus: 'Military status',
    visibleForMales: 'Required for male applicants',
    selectOption: 'Select an option',
    completed: 'Completed',
    exempted: 'Exempted',
    postponed: 'Postponed',
    currentlyServing: 'Currently serving',
    phoneNumber: 'Phone number',
    address: 'Address',
    governorate: 'Governorate',
    preferredLanguage: 'Preferred language',
    english: 'English',
    arabic: 'Arabic',
    gmailNotifications: 'Gmail notifications',
    gmailHint: 'Receive application updates by email.',
    university: 'University',
    faculty: 'Faculty',
    degreeLevel: 'Degree level',
    major: 'Major',
    graduationYear: 'Graduation year',
    cumulativeGrade: 'Cumulative grade',
    acceptable: 'Acceptable',
    good: 'Good',
    veryGood: 'Very good',
    excellent: 'Excellent',
    back: 'Back',
    next: 'Next step',
    save: 'Save profile',
    saveEditable: 'Save editable changes',
    saving: 'Saving…',
    required: 'This field is required.',
    englishNameOnly:
      'Use English letters only. Spaces, apostrophes, periods, and hyphens are allowed.',
    arabicNameOnly:
      'Use Arabic letters only. Spaces, apostrophes, periods, and hyphens are allowed.',
    nationalIdFormat: 'Enter exactly 14 digits.',
    pastDate: 'Date of birth must be in the past.',
    graduationYearRange: 'Enter a year between 1900 and',
    phoneFormat: 'Enter a valid phone number.',
    maximumLength: 'This value is too long.',
  },
  ar: {
    title: 'استكمال الملف الشخصي',
    lockedTitle: 'مراجعة الملف الشخصي',
    subtitle: 'أكمل الخطوات الثلاث لإنهاء ملف التقديم.',
    lockedSubtitle: 'راجع بياناتك وحافظ على تحديث معلومات التواصل.',
    lockedBanner:
      'المراجعة جارية. تم قفل بيانات الأهلية والبيانات الأكاديمية بعد تقديم الطلب.',
    lockedHint: 'مقفل بعد تقديم الطلب',
    loadErrorTitle: 'تعذر تحميل ملفك الشخصي',
    retry: 'إعادة المحاولة',
    loading: 'جارٍ تحميل ملفك الشخصي…',
    complete: 'الملف مكتمل',
    saved: 'تم حفظ ملفك الشخصي.',
    saveErrorTitle: 'تعذر حفظ التغييرات',
    validationSummary: 'راجع الحقول المحددة ثم حاول مرة أخرى.',
    stepsAriaLabel: 'خطوات استكمال الملف الشخصي',
    personalStep: 'البيانات الشخصية',
    contactStep: 'بيانات التواصل',
    academicStep: 'البيانات الأكاديمية',
    personalTitle: 'المعلومات الشخصية',
    contactTitle: 'التواصل والتفضيلات',
    academicTitle: 'المعلومات الأكاديمية',
    fullNameEn: 'الاسم بالكامل بالإنجليزية',
    fullNameAr: 'الاسم بالكامل بالعربية',
    nationalId: 'الرقم القومي المكون من 14 رقمًا',
    nationality: 'الجنسية',
    egyptian: 'مصري',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'النوع',
    male: 'ذكر',
    female: 'أنثى',
    militaryStatus: 'الموقف من التجنيد',
    visibleForMales: 'مطلوب للمتقدمين الذكور',
    selectOption: 'اختر',
    completed: 'أدى الخدمة',
    exempted: 'معفى',
    postponed: 'مؤجل',
    currentlyServing: 'يؤدي الخدمة حاليًا',
    phoneNumber: 'رقم الهاتف',
    address: 'العنوان',
    governorate: 'المحافظة',
    preferredLanguage: 'اللغة المفضلة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    gmailNotifications: 'إشعارات البريد الإلكتروني',
    gmailHint: 'استقبل تحديثات طلبك عبر البريد الإلكتروني.',
    university: 'الجامعة',
    faculty: 'الكلية',
    degreeLevel: 'الدرجة العلمية',
    major: 'التخصص',
    graduationYear: 'سنة التخرج',
    cumulativeGrade: 'التقدير التراكمي',
    acceptable: 'مقبول',
    good: 'جيد',
    veryGood: 'جيد جدًا',
    excellent: 'امتياز',
    back: 'السابق',
    next: 'الخطوة التالية',
    save: 'حفظ الملف',
    saveEditable: 'حفظ التغييرات المتاحة',
    saving: 'جارٍ الحفظ…',
    required: 'هذا الحقل مطلوب.',
    englishNameOnly:
      'استخدم الحروف الإنجليزية فقط. يُسمح بالمسافات والفواصل العليا والنقاط والشرطات.',
    arabicNameOnly:
      'استخدم الحروف العربية فقط. يُسمح بالمسافات والفواصل العليا والنقاط والشرطات.',
    nationalIdFormat: 'أدخل 14 رقمًا بالضبط.',
    pastDate: 'يجب أن يكون تاريخ الميلاد في الماضي.',
    graduationYearRange: 'أدخل سنة بين 1900 و',
    phoneFormat: 'أدخل رقم هاتف صحيحًا.',
    maximumLength: 'القيمة أطول من الحد المسموح.',
  },
} as const;
