export const HUMAN_REVIEW_COPY = {
  en: {
    common: {
      retry: 'Try again',
      cancel: 'Cancel',
      close: 'Close',
      unknownApplicant: 'Applicant name unavailable',
      unavailable: 'Not available',
      documentTypes: {
        None: 'Unknown document',
        NationalId: 'National ID',
        BirthCertificate: 'Birth certificate',
        GraduationCertificate: 'Graduation certificate',
        MilitaryCertificate: 'Military certificate',
      },
      statuses: {
        None: 'Unknown',
        Uploaded: 'Uploaded',
        Verifying: 'Verifying',
        Approved: 'Approved',
        NeedsHumanReview: 'Needs human review',
        ReplacementRequested: 'Replacement requested',
        Rejected: 'Rejected',
      },
      fieldNames: {
        FullNameAr: 'Full name in Arabic',
        FullNameEn: 'Full name in English',
        NationalId: 'National ID',
        DateOfBirth: 'Date of birth',
        Nationality: 'Nationality',
        University: 'University',
        Faculty: 'Faculty',
        GraduationYear: 'Graduation year',
        CumulativeGrade: 'Cumulative grade',
        MilitaryStatus: 'Military status',
      },
    },
    queue: {
      eyebrow: 'Operations · Human review',
      title: 'Document Review Queue',
      subtitle: 'Review documents that require a verified human decision.',
      pending: 'Total pending',
      refresh: 'Refresh',
      refreshing: 'Refreshing…',
      search: 'Search applicant or filename',
      documentType: 'Document type',
      allDocumentTypes: 'All document types',
      status: 'Status',
      allStatuses: 'All statuses',
      sort: 'Sort',
      newest: 'Newest first',
      oldest: 'Oldest first',
      clearFilters: 'Clear filters',
      applicant: 'Applicant name',
      action: 'Action',
      review: 'Review',
      loading: 'Loading review queue',
      loadingCopy: 'Retrieving documents awaiting staff review.',
      errorTitle: 'The review queue could not be loaded',
      errorCopy: 'Check your connection and try again.',
      emptyTitle: 'Queue is clear',
      emptyCopy: 'There are currently no documents awaiting human review.',
      noResultsTitle: 'No matching documents',
      noResultsCopy: 'No review items match the current search and filters.',
      results: 'Showing {{from}}–{{to}} of {{total}} results',
      previousPage: 'Previous page',
      nextPage: 'Next page',
      page: 'Page {{page}} of {{total}}',
      approvedSuccess: 'The document was approved successfully.',
      rejectedSuccess: 'The document was rejected and the applicant was notified.',
      replacementSuccess: 'A document replacement request was sent to the applicant.',
    },
    details: {
      back: 'Review queue',
      title: 'Document Review Detail',
      subtitle: 'Compare the uploaded document with the applicant data before deciding.',
      loading: 'Loading document review',
      errorTitle: 'The document review could not be loaded',
      errorCopy: 'The document may no longer be available or the request failed.',
      fileLoading: 'Loading secure document',
      fileErrorTitle: 'The document file could not be displayed',
      fileErrorCopy: 'You can retry loading the secure file without reloading the review.',
      retryFile: 'Retry file',
      aiLabel: 'AI-assisted review',
      aiStatus: 'AI Verification Status',
      aiAdvisory: 'AI findings support this review; the final decision is made by staff.',
      model: 'Model',
      confidence: 'Confidence score',
      verificationUnavailable: 'Verification details unavailable',
      verificationUnavailableCopy: 'No valid verification JSON was returned for this document.',
      warnings: 'Warnings',
      missingFields: 'Missing fields',
      comparison: 'Data Extraction Comparison',
      field: 'Field',
      applicantData: 'Applicant data',
      extractedData: 'AI extracted data',
      match: 'Match',
      notes: 'Notes',
      matched: 'Matched',
      mismatched: 'Mismatch',
      discrepancy: 'Discrepancy detected',
      noFields: 'No comparison fields were provided.',
      approve: 'Approve',
      reject: 'Reject',
      requestReplacement: 'Request replacement',
      replacementSent: 'Replacement request was sent.',
      actionError: 'The action could not be completed. Please try again.',
      documentType: 'Document type',
      fileName: 'Original filename',
    },
    approve: {
      title: 'Approve document?',
      message:
        'Confirm that this document satisfies the review requirements. The applicant will be notified.',
      confirm: 'Confirm approval',
      confirming: 'Approving…',
    },
    reject: {
      title: 'Reject Document — Action Required',
      explanation:
        'Rejecting this document will notify the applicant and mark the document as rejected.',
      label: 'Reason sent to applicant',
      required: 'Required',
      placeholder: 'Provide a clear reason for the applicant…',
      helper: 'Explain what is missing or incorrect and what the applicant should do next.',
      quickInsert: 'Quick insert',
      illegible: 'Illegible / Blurry',
      missingPages: 'Missing Pages',
      unofficial: 'Not Official Document',
      incorrect: 'Incorrect Information',
      confirm: 'Confirm rejection',
      confirming: 'Rejecting…',
      requiredError: 'Enter an applicant-visible rejection reason.',
      lengthError: 'Use between 10 and 1,000 characters.',
    },
    replacement: {
      title: 'Request Document Replacement',
      explanation: 'The applicant will be notified and asked to upload a replacement document.',
      label: 'Replacement reason sent to applicant',
      required: 'Required',
      placeholder: 'Explain why a replacement document is required…',
      helper: 'Give the applicant clear instructions for the replacement upload.',
      quickInsert: 'Quick insert',
      expired: 'Expired document',
      illegible: 'Illegible or blurry',
      missingPages: 'Missing pages',
      incorrectDocument: 'Incorrect document',
      mismatch: 'Information does not match',
      confirm: 'Confirm request',
      confirming: 'Sending…',
      requiredError: 'Enter an applicant-visible replacement reason.',
      lengthError: 'Use between 10 and 1,000 characters.',
    },
    viewer: {
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      rotate: 'Rotate clockwise',
      reset: 'Reset view',
      download: 'Download document',
      documentPreview: 'Secure document preview',
      unsupported: 'This file type cannot be previewed. Download it to review the document.',
    },
  },
  ar: {
    common: {
      retry: 'حاول مرة أخرى',
      cancel: 'إلغاء',
      close: 'إغلاق',
      unknownApplicant: 'اسم المتقدم غير متاح',
      unavailable: 'غير متاح',
      documentTypes: {
        None: 'مستند غير معروف',
        NationalId: 'بطاقة الرقم القومي',
        BirthCertificate: 'شهادة الميلاد',
        GraduationCertificate: 'شهادة التخرج',
        MilitaryCertificate: 'شهادة الموقف من التجنيد',
      },
      statuses: {
        None: 'غير معروف',
        Uploaded: 'تم الرفع',
        Verifying: 'جارٍ التحقق',
        Approved: 'مقبول',
        NeedsHumanReview: 'يحتاج مراجعة بشرية',
        ReplacementRequested: 'طُلب الاستبدال',
        Rejected: 'مرفوض',
      },
      fieldNames: {
        FullNameAr: 'الاسم الكامل بالعربية',
        FullNameEn: 'الاسم الكامل بالإنجليزية',
        NationalId: 'الرقم القومي',
        DateOfBirth: 'تاريخ الميلاد',
        Nationality: 'الجنسية',
        University: 'الجامعة',
        Faculty: 'الكلية',
        GraduationYear: 'سنة التخرج',
        CumulativeGrade: 'التقدير التراكمي',
        MilitaryStatus: 'الموقف من التجنيد',
      },
    },
    queue: {
      eyebrow: 'العمليات · المراجعة البشرية',
      title: 'قائمة مراجعة المستندات',
      subtitle: 'راجع المستندات التي تتطلب قرارًا بشريًا موثقًا.',
      pending: 'إجمالي المنتظر',
      refresh: 'تحديث',
      refreshing: 'جارٍ التحديث…',
      search: 'ابحث باسم المتقدم أو اسم الملف',
      documentType: 'نوع المستند',
      allDocumentTypes: 'كل أنواع المستندات',
      status: 'الحالة',
      allStatuses: 'كل الحالات',
      sort: 'الترتيب',
      newest: 'الأحدث أولًا',
      oldest: 'الأقدم أولًا',
      clearFilters: 'مسح عوامل التصفية',
      applicant: 'اسم المتقدم',
      action: 'الإجراء',
      review: 'مراجعة',
      loading: 'جارٍ تحميل قائمة المراجعة',
      loadingCopy: 'جارٍ استرجاع المستندات المنتظرة لمراجعة فريق العمليات.',
      errorTitle: 'تعذر تحميل قائمة المراجعة',
      errorCopy: 'تحقق من الاتصال ثم حاول مرة أخرى.',
      emptyTitle: 'قائمة المراجعة خالية',
      emptyCopy: 'لا توجد مستندات تنتظر المراجعة البشرية حاليًا.',
      noResultsTitle: 'لا توجد مستندات مطابقة',
      noResultsCopy: 'لا توجد عناصر تطابق البحث وعوامل التصفية الحالية.',
      results: 'عرض {{from}}–{{to}} من {{total}} نتيجة',
      previousPage: 'الصفحة السابقة',
      nextPage: 'الصفحة التالية',
      page: 'الصفحة {{page}} من {{total}}',
      approvedSuccess: 'تم قبول المستند بنجاح.',
      rejectedSuccess: 'تم رفض المستند وإخطار المتقدم.',
      replacementSuccess: 'تم إرسال طلب استبدال المستند إلى المتقدم.',
    },
    details: {
      back: 'قائمة المراجعة',
      title: 'تفاصيل مراجعة المستند',
      subtitle: 'قارن المستند المرفوع ببيانات المتقدم قبل اتخاذ القرار.',
      loading: 'جارٍ تحميل مراجعة المستند',
      errorTitle: 'تعذر تحميل مراجعة المستند',
      errorCopy: 'قد لا يكون المستند متاحًا أو قد فشل الطلب.',
      fileLoading: 'جارٍ تحميل المستند الآمن',
      fileErrorTitle: 'تعذر عرض ملف المستند',
      fileErrorCopy: 'يمكنك إعادة تحميل الملف الآمن دون إعادة تحميل المراجعة.',
      retryFile: 'إعادة تحميل الملف',
      aiLabel: 'مراجعة بمساعدة الذكاء الاصطناعي',
      aiStatus: 'حالة تحقق الذكاء الاصطناعي',
      aiAdvisory: 'تدعم نتائج الذكاء الاصطناعي هذه المراجعة، ويتخذ فريق العمليات القرار النهائي.',
      model: 'النموذج',
      confidence: 'درجة الثقة',
      verificationUnavailable: 'تفاصيل التحقق غير متاحة',
      verificationUnavailableCopy: 'لم يتم إرجاع بيانات تحقق صالحة لهذا المستند.',
      warnings: 'التحذيرات',
      missingFields: 'الحقول المفقودة',
      comparison: 'مقارنة البيانات المستخرجة',
      field: 'الحقل',
      applicantData: 'بيانات المتقدم',
      extractedData: 'بيانات الذكاء الاصطناعي',
      match: 'التطابق',
      notes: 'ملاحظات',
      matched: 'متطابق',
      mismatched: 'غير متطابق',
      discrepancy: 'تم اكتشاف اختلاف',
      noFields: 'لم يتم توفير حقول للمقارنة.',
      approve: 'قبول',
      reject: 'رفض',
      requestReplacement: 'طلب استبدال',
      replacementSent: 'تم إرسال طلب الاستبدال.',
      actionError: 'تعذر إكمال الإجراء. حاول مرة أخرى.',
      documentType: 'نوع المستند',
      fileName: 'اسم الملف الأصلي',
    },
    approve: {
      title: 'قبول المستند؟',
      message: 'أكد أن المستند يستوفي متطلبات المراجعة. سيتم إخطار المتقدم.',
      confirm: 'تأكيد القبول',
      confirming: 'جارٍ القبول…',
    },
    reject: {
      title: 'رفض المستند — يلزم اتخاذ إجراء',
      explanation: 'سيؤدي رفض المستند إلى إخطار المتقدم وتغيير حالة المستند إلى مرفوض.',
      label: 'السبب المرسل إلى المتقدم',
      required: 'مطلوب',
      placeholder: 'اكتب سببًا واضحًا للمتقدم…',
      helper: 'وضح ما هو مفقود أو غير صحيح وما الذي يجب على المتقدم فعله.',
      quickInsert: 'إدراج سريع',
      illegible: 'غير واضح / ضبابي',
      missingPages: 'صفحات مفقودة',
      unofficial: 'مستند غير رسمي',
      incorrect: 'معلومات غير صحيحة',
      confirm: 'تأكيد الرفض',
      confirming: 'جارٍ الرفض…',
      requiredError: 'أدخل سبب الرفض الذي سيظهر للمتقدم.',
      lengthError: 'استخدم من 10 إلى 1000 حرف.',
    },
    replacement: {
      title: 'طلب استبدال المستند',
      explanation: 'سيتم إخطار المتقدم ومطالبته برفع مستند بديل.',
      label: 'سبب الاستبدال المرسل إلى المتقدم',
      required: 'مطلوب',
      placeholder: 'وضح سبب الحاجة إلى مستند بديل…',
      helper: 'قدم للمتقدم تعليمات واضحة لرفع المستند البديل.',
      quickInsert: 'إدراج سريع',
      expired: 'المستند منتهي الصلاحية',
      illegible: 'غير واضح أو ضبابي',
      missingPages: 'صفحات مفقودة',
      incorrectDocument: 'مستند غير صحيح',
      mismatch: 'المعلومات غير متطابقة',
      confirm: 'تأكيد الطلب',
      confirming: 'جارٍ الإرسال…',
      requiredError: 'أدخل سبب الاستبدال الذي سيظهر للمتقدم.',
      lengthError: 'استخدم من 10 إلى 1000 حرف.',
    },
    viewer: {
      zoomIn: 'تكبير',
      zoomOut: 'تصغير',
      rotate: 'تدوير مع عقارب الساعة',
      reset: 'إعادة ضبط العرض',
      download: 'تنزيل المستند',
      documentPreview: 'معاينة آمنة للمستند',
      unsupported: 'لا يمكن معاينة هذا النوع من الملفات. نزّله لمراجعة المستند.',
    },
  },
} as const;
