/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#022448',
        'primary-container': '#1e3a5f',
        'on-primary': '#ffffff',
        secondary: '#505f76',
        'secondary-container': '#d0e1fb',
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'on-surface': '#191c1e',
        'on-surface-variant': '#43474e',
        'on-background': '#191c1e',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        success: '#065f46',
        'success-container': '#d1fae5',
        warning: '#d8953a',
        'warning-container': '#ffddb8',
        // Colors from Stitch UI Design
        "surface-dim": "#d8dadc",
        "on-primary-container": "#8aa4cf",
        "on-secondary": "#ffffff",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-container": "#54647a",
        "secondary": "#505f76",
        "surface-container-low": "#f2f4f6",
        "outline": "#74777f",
        "surface-tint": "#455f87",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#d3e4fe",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001c3b",
        "secondary-container": "#d0e1fb",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#adc8f5",
        "tertiary-container": "#533200",
        "primary-container": "#1e3a5f",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#d8953a",
        "inverse-on-surface": "#eff1f3",
        "primary": "#022448",
        "background": "#f7f9fb",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#2d486d",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c4c6cf",
        "primary-fixed": "#d5e3ff",
        "on-surface-variant": "#43474e",
        "tertiary": "#361f00",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#0b1c30",
        "inverse-primary": "#adc8f5",
        "on-background": "#191c1e"
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'Arial', 'sans-serif'],
        // Font families from Stitch UI Design
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "headline-xl": ["IBM Plex Sans", "sans-serif"]
      },
      borderRadius: {
        control: '0.25rem',
        card: '0.5rem',
        panel: '0.75rem',
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "280px",
        "gutter": "1.5rem",
        "stack-gap": "1rem",
        "container-max": "1280px",
        "margin-page": "2rem"
      },
      fontSize: {
        // Font sizes & weights from Stitch UI Design
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "1.2", fontWeight: "600" }]
      },
      boxShadow: {
        card: '0 2px 8px rgb(2 36 72 / 8%)',
      },
    },
  },
  plugins: [],
};
